// <auto-generated />
namespace TaskCodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCashOperationType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCashOperationType));
        
        string IMigrationMetadata.Id
        {
            get { return "201309301813532_AddCashOperationType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
